### ISSUE TITLE
Unicode letters in author names don't appear to be parsed correctly

### ISSUE THREAD

**Issue by carbocation** [CBIIT/nci-webtools-dceg-author-arranger#5]
AuthorArranger is a fantastic tool and I recommend it to everyone. One apparent bug: I am fortunate to have coauthors from around the globe, some of whom have characters like "ä" in their names. This doesn't seem to be parsed correctly by AuthorArranger (output as "Ã¤"). It would be helpful if unicode characters were not modified.

**Comment by park-brian** [comment]
Hello, if you're using text files, can you make sure they're saved as UTF-8 with BOM? Alternatively, you can also try using xlsx files.

**Comment by carbocation** [comment]
This indeed works correctly for me with xlsx files, thanks.
